### ISSUE TITLE
Addon showing Zee error

### ISSUE THREAD

**Issue by DTonline** [mavwolverine/mavwolverine-kodi#1]
Both the Zee and Zee Marathi addon  are showing Zee/ Zee Marathi error. Probably a file access issue. While at it can we have an addon for &TV?

**Comment by mavwolverine** [comment]
Not sure I understand your problem. Also what is &TV?

**Comment by DTonline** [comment]
Hello Viraj:
Thanks for looking into this issue. When I launch the Zee Marathi or the Zee Tv add on on kodi either on a PC or on the Amazon Fire Stick the  various shows are displayed as before. The shows lists even updates daily to show the new episodes but if you click on any of the episodes to actually play it, you get an error message "Zee Marathi (or Zee TV) error check the log for more information". The addon version is 0.0.3 on both devices. The kodi log from my PC can be seen at http:// xbmclogs.com/poasijgoq hope this helps. 
As for &Tv, this is a Zee tv channel just like the others. It's website is www.andtv.com, this channel is fairly new( I think) but interesting.
Thanks for your help. 
Regards,
Dnyanesh

-----Original Message-----

**Comment by mavwolverine** [comment]
The official Kodi repo no longer gets updated plugins. Kodi received a copyright notice from Zee. You will have to manually install the latest version from the repo.

ZEE TV will no longer work as they now provide only 6 min videos on their website. So the plugin will only show those videos.

&TV seems to be Zee venture and they might be doing the same.

**Comment by sanketkudav** [comment]
Hey Viraj,

I have no idea how to manually install the latest version. I can't seem to follow the instructions you have provided, mainly because I'm fairly new to this. Can you help me out?

Thanks.

**Comment by prinzen150** [comment]
Hi Viraj, I am using Kodi version jarvis 16.1 and get error when launching zee marathi addon 0.5. can u advise pls?
